[package]
name = "geekcom-core"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
serialport = "4.8"
serde = { version = "1", features = ["derive"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Devices_Communication", "Win32_Foundation"] }
